blank_issues_enabled: false
contact_links:
  - name: Sponge Docs
    url: https://docs.spongepowered.org/
    about: Read these
  - name: Sponge Forums
    url: https://forums.spongepowered.org/
    about: Forums
